version: '3.3'

services:
    django:
        build:
            context: ./iago
            dockerfile: Dockerfile
        volumes:
            - ./iago:/iago/
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - 5678:5678
        # stdin_open: true
        # tty: true

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 8000:80
        restart: unless-stopped
        depends_on:
            - django

    # redis:
    #     image: redis

    # datadog:
    #     build: datadog
    #     links:
    #         - redis # ensures that redis is a host that the container can find
    #         - django # ensures that the web app can send metrics
    #     environment:
    #         - DD_API_KEY=dddddd
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #         - /proc/:/host/proc/:ro
    #         - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
