org: jeenyai
app: iago
service: jeeny-dynamodb-content
frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  region: eu-central-1

# https://www.serverless.com/guides/dynamodb
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: source_url
            AttributeType: S
          - AttributeName: author
            AttributeType: S
          - AttributeName: title
            AttributeType: S
          - AttributeName: content
            AttributeType: S
          # https://en.wikipedia.org/wiki/ISO_8601
          - AttributeName: created_on
            AttributeType: S
          - AttributeName: updated_on
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: jeeny-content
