service: iago-serverless
app: iago
org: jeenyai

frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-python-requirements

custom:
  customDomain:
    domainName: serverless.iago.jeeny.ai
    certificateName: "*.iago.jeeny.ai"
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: http

provider:
  name: aws
  stage: dev
  region: eu-central-1
  architecture: arm64

functions:
  transformer:
    memorySize: 6064
    timeout: 30
    image: 237339178325.dkr.ecr.eu-central-1.amazonaws.com/iago-serverless-transformer:latest
    events:
      - httpApi:
          method: get
          path: /transform
  medium_post_data:
    memorySize: 256
    handler: medium/medium_handler.handler
    timeout: 6
    events:
      - httpApi:
          method: get
          path: /medium/{url}
