service: iago-serverless
app: iago
org: jeenyai

frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  region: eu-central-1
  architecture: arm64

  # iam:
  #   role:
  #     statements:
  #       - Effect: "Allow"
  #         Action:
  #           - "s3:ListBucket"
  #           - "s3:PutObject"
  #         Resource:
  #           Fn::Join:
  #             - ""
  #             - - "arn:aws:s3:::"
  #               - "Ref": "ServerlessDeploymentBucket"
  #               - "/*"

#  environment:
#    variable1: value1

functions:
  transformer:
    memorySize: 6064
    timeout: 45 
    image: 237339178325.dkr.ecr.eu-central-1.amazonaws.com/iago-serverless-transformer:latest
    events:
      - httpApi:
          path: /
          method: get
# https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml#aws-resources
