# Generated by Django 3.2.8 on 2021-10-28 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0004_cachedjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedjson',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
