# Generated by Django 3.2.8 on 2021-11-04 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0005_cachedjson_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('FINISHED', 'Finished'), ('ERRORED', 'Errored')], default='QUEUED', max_length=15)),
                ('url_submitted', models.URLField(max_length=800)),
                ('url_response', models.URLField(blank=True, max_length=800, null=True)),
                ('datetime_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('diffbot_response', models.JSONField(blank=True, default=dict, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('isEnglish', models.BooleanField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
