# Generated by Django 3.2.8 on 2021-11-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0006_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='isArticle',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
