# Generated by Django 3.2.8 on 2021-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0008_alter_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='content',
            name='diffbot_response',
            field=models.JSONField(default=dict),
        ),
    ]
