# Generated by Django 3.2.8 on 2021-11-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0009_auto_20211106_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='environment',
            field=models.CharField(choices=[('LIVE', 'live'), ('TEST', 'test')], default='TEST', max_length=15),
        ),
    ]
