# Generated by Django 3.2.8 on 2021-11-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0010_content_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='inferences',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='content',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
