# Generated by Django 3.2.8 on 2021-11-29 00:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0013_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='embeddings',
        ),
        migrations.AddField(
            model_name='content',
            name='embedding_all_mpnet_base_v2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
