# Generated by Django 4.0.2 on 2022-02-14 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0014_auto_20211129_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('embedding_all_mpnet_base_v2', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=768)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('embedding_all_mpnet_base_v2', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=768)),
            ],
        ),
    ]
