# Generated by Django 4.0.3 on 2022-03-23 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0016_scrapedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedarticle',
            name='embedding_all_mpnet_base_v2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
        migrations.AddField(
            model_name='scrapedarticle',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
