# Generated by Django 4.0.3 on 2022-03-30 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0017_scrapedarticle_embedding_all_mpnet_base_v2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCluster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('k_top', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='v0.skill')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='CachedJSON',
        ),
        migrations.AddField(
            model_name='skill',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v0.skillcluster'),
        ),
    ]
