# Generated by Django 4.0.3 on 2022-03-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0018_skillcluster_delete_article_delete_cachedjson_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='scrapedarticle',
            name='popularity',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scrapedarticle',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='v0.skill'),
        ),
    ]
