# Generated by Django 4.0.3 on 2022-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0019_delete_content_scrapedarticle_popularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedarticle',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('pdf', 'Pdf')], default='article', max_length=10),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='skills',
            field=models.ManyToManyField(to='v0.skill'),
        ),
    ]
