# Generated by Django 4.0.2 on 2022-04-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0020_scrapedarticle_type_alter_scrapedarticle_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapedArticle',
            new_name='Content',
        ),
        migrations.AlterField(
            model_name='content',
            name='skills',
            field=models.ManyToManyField(to='v0.Skill'),
        ),
    ]
