# Generated by Django 4.0.3 on 2022-04-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0021_rename_scrapedarticle_content_alter_content_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
