# Generated by Django 4.0.3 on 2022-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0022_content_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
