# Generated by Django 4.0.4 on 2022-05-30 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0024_imagecollection_content_thumbnail_alternatives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(editable=False, max_length=800, unique=True)),
                ('domain', models.CharField(editable=False, max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url_alive', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('unsplash', 'Unsplash'), ('pexels', 'Pexels'), ('shutterstock', 'Shutterstock'), ('gcc_dataset', 'Google Conceptual Captions Dataset')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageCollection',
        ),
        migrations.RemoveField(
            model_name='content',
            name='thumbnail_alternatives',
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail_alternative_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail_alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v0.image'),
        ),
    ]
