# Generated by Django 4.0.4 on 2022-05-30 14:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0027_image_embedding_all_mpnet_base_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='embedding_all_mpnet_base_v2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=768),
        ),
    ]
