# Generated by Django 4.0.4 on 2022-05-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0028_alter_image_embedding_all_mpnet_base_v2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='provider',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='domain',
            new_name='provider'
        )
    ]
