# Generated by Django 4.0.4 on 2022-06-16 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0029_remove_image_domain_image_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsplashCollection',
            fields=[
                ('photo_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('collection_id', models.CharField(max_length=11)),
                ('collection_title', models.TextField(blank=True, null=True)),
                ('photo_collected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unsplash_collections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnsplashColor',
            fields=[
                ('photo_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('hex', models.CharField(max_length=6)),
                ('red', models.IntegerField(blank=True, null=True)),
                ('green', models.IntegerField(blank=True, null=True)),
                ('blue', models.IntegerField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_coverage', models.FloatField(blank=True, null=True)),
                ('ai_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unsplash_colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnsplashConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_type', models.CharField(blank=True, max_length=255, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
                ('photo_id', models.CharField(blank=True, max_length=11, null=True)),
                ('anonymous_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('conversion_country', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'unsplash_conversions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnsplashKeyword',
            fields=[
                ('photo_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('keyword', models.TextField()),
                ('ai_service_1_confidence', models.FloatField(blank=True, null=True)),
                ('ai_service_2_confidence', models.FloatField(blank=True, null=True)),
                ('suggested_by_user', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unsplash_keywords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnsplashPhoto',
            fields=[
                ('photo_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('photo_featured', models.BooleanField(blank=True, null=True)),
                ('photo_width', models.IntegerField(blank=True, null=True)),
                ('photo_height', models.IntegerField(blank=True, null=True)),
                ('photo_aspect_ratio', models.FloatField(blank=True, null=True)),
                ('photo_description', models.TextField(blank=True, null=True)),
                ('photographer_username', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('exif_camera_make', models.CharField(blank=True, max_length=255, null=True)),
                ('exif_camera_model', models.CharField(blank=True, max_length=255, null=True)),
                ('exif_iso', models.IntegerField(blank=True, null=True)),
                ('exif_aperture_value', models.CharField(blank=True, max_length=255, null=True)),
                ('exif_focal_length', models.CharField(blank=True, max_length=255, null=True)),
                ('exif_exposure_time', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_location_latitude', models.FloatField(blank=True, null=True)),
                ('photo_location_longitude', models.FloatField(blank=True, null=True)),
                ('photo_location_country', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('stats_views', models.IntegerField(blank=True, null=True)),
                ('stats_downloads', models.IntegerField(blank=True, null=True)),
                ('ai_description', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_primary_landmark_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_primary_landmark_latitude', models.FloatField(blank=True, null=True)),
                ('ai_primary_landmark_longitude', models.FloatField(blank=True, null=True)),
                ('ai_primary_landmark_confidence', models.CharField(blank=True, max_length=255, null=True)),
                ('blur_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'unsplash_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenericStringEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='thumbnail_alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v0.unsplashphoto'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
