# Generated by Django 4.0.4 on 2022-06-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0032_alter_genericstringembedding_embedding_all_mpnet_base_v2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericstringembedding',
            name='name',
            field=models.TextField(default='', editable=False, primary_key=True, serialize=False),
        ),
    ]
