# Generated by Django 4.0.4 on 2022-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0034_alter_genericstringembedding_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericstringembedding',
            name='name',
            field=models.TextField(editable=False),
        ),
        migrations.AddField(
            model_name='genericstringembedding',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
