# Generated by Django 4.0.4 on 2022-06-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0035_genericstringembedding_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='last_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='content',
            name='markdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='summary',
            field=models.JSONField(default=dict),
        ),
    ]
