# Generated by Django 4.0.4 on 2022-06-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0036_content_last_response_content_markdown_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unsplashphoto',
            options={},
        ),
    ]
