# Generated by Django 4.0.4 on 2022-06-20 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0037_alter_unsplashphoto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unsplashcollection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unsplashcolor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unsplashconversion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unsplashkeyword',
            options={},
        ),
        migrations.AddField(
            model_name='unsplashphoto',
            name='embedding_all_mpnet_base_v2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
    ]
