# Generated by Django 4.0.5 on 2022-07-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0038_alter_unsplashcollection_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unsplashcollection',
            unique_together={('photo_id', 'collection_id')},
        ),
        migrations.AlterUniqueTogether(
            name='unsplashcolor',
            unique_together={('photo_id', 'hex')},
        ),
        migrations.AlterUniqueTogether(
            name='unsplashkeyword',
            unique_together={('photo_id', 'keyword')},
        ),
    ]
