# Generated by Django 4.0.5 on 2022-07-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0039_alter_unsplashcollection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='provider',
            field=models.CharField(choices=[('medium', 'Medium'), ('hbr', 'Hbr'), ('vodafone', 'Vodafone')], default='medium', max_length=25),
        ),
    ]
