# Generated by Django 4.0.5 on 2022-07-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0040_content_file_alter_content_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_read_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
