# Generated by Django 4.0.5 on 2022-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0041_alter_content_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('pdf', 'Pdf'), ('invalid_file', 'Invalid File')], default='article', max_length=25),
        ),
    ]
