# Generated by Django 4.0.6 on 2022-07-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0042_alter_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
