# Generated by Django 4.0.5 on 2022-07-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0043_content_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='thumbnail_alternative_url',
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail_original',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
