# Generated by Django 4.0.5 on 2022-07-19 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0044_remove_content_thumbnail_alternative_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindtoolSkill',
            fields=[
                ('name', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('embedding_all_mpnet_base_v2', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=768)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
