# Generated by Django 4.0.5 on 2022-07-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0046_rename_mindtoolskill_mindtoolsskillgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='thumbnail',
            field=models.URLField(default='https://images.unsplash.com/photo-1499988921418-b7df40ff03f9'),
        ),
    ]
