# Generated by Django 4.0.6 on 2022-08-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v0', '0048_content_mindtools_skill_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='mindtools_skill_group',
        ),
        migrations.AddField(
            model_name='content',
            name='mindtools_skill_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v0.mindtoolsskillgroup'),
        ),
        migrations.RemoveField(
            model_name='content',
            name='mindtools_skill_subgroup',
        ),
        migrations.AddField(
            model_name='content',
            name='mindtools_skill_subgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='v0.mindtoolsskillsubgroup'),
        ),
    ]
