# Generated by Django 3.2.8 on 2021-10-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_engine', '0002_alter_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
