# Generated by Django 3.2.8 on 2021-10-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_engine', '0003_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedJSON',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cachedjson',
            },
        ),
    ]
