"""empty message

Revision ID: 4b61ab0ff92a
Revises: 
Create Date: 2022-02-14 18:00:02.122097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b61ab0ff92a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'jobtitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index('ix_jobs___ts_vector__', 'jobs', ['__ts_vector__'], unique=False, postgresql_using='gin')
    op.create_unique_constraint(None, 'jobs', ['jobtitle'])
    op.alter_column('skills', 'skill',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'skills', ['skill'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    op.alter_column('skills', 'skill',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'jobs', type_='unique')
    op.drop_index('ix_jobs___ts_vector__', table_name='jobs', postgresql_using='gin')
    op.alter_column('jobs', 'jobtitle',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
